# Generated by Django 5.0.6 on 2024-07-08 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasons', '0002_user_preferred_name_alter_user_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reason',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_reason_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelOptions(
            name='reason',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='reason',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_reason_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PartnershipUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reasons.partnership')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
