# Generated by Django 5.0.6 on 2024-07-08 02:09

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasons', '0003_alter_reason_author_alter_reason_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='users',
            field=models.ManyToManyField(through='reasons.PartnershipUser', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='partnershipuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='partnershipuser',
            name='nickname',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reason',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
